### ISSUE TITLE
Broken E2E test

### ISSUE THREAD

**Issue by SDohle** [rosen-group/ngx-onboarding#41]
Sample App E2E Test is broken:

1) workspace-project App should show onboarding overlay initially and hide it if "Turn Off" button is clicked
  - Failed: Wait timed out after 10009ms

```
(...)
          at AppPage.waitAndCountOnboardingHeader (/home/steffen/git/github/ngx-onboarding/e2e/src/app.po.ts:25:17)
          at UserContext.<anonymous> (/home/steffen/git/github/ngx-onboarding/e2e/src/app.e2e-spec.ts:23:21)
(...)
```

**Comment by SDohle** [comment]
Onboarding isn't active at startup with cleared local storge

**Comment by miller45** [comment]
The "problem" is that the onboarding was automatically active in the past (regardless of localstorage)
